export const AUTHENTICATION_TITLE = 'Authentication';

// Key Http Request
export const AUTHENTICATION_CREATE_NEW_PASSWORD_REQUEST = 'AUTHENTICATION_CREATE_NEW_PASSWORD_REQUEST';
export const AUTHENTICATION_SIGN_IN_REQUEST = 'AUTHENTICATION_SIGN_IN_REQUEST';
export const AUTHENTICATION_RESET_PASSWORD_REQUEST = 'AUTHENTICATION_RESET_PASSWORD_REQUEST';
