/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBaseFormGroup: typeof import('@components/base/AppBaseFormGroup.vue')['default']
    AppBaseSvg: typeof import('@components/base/AppBaseSvg.vue')['default']
    AppBaseToast: typeof import('@components/base/AppBaseToast.vue')['default']
    PrimeVueAvatar: typeof import('primevue/avatar')['default']
    PrimeVueButton: typeof import('primevue/button')['default']
    PrimeVueCard: typeof import('primevue/card')['default']
    PrimeVueCheckbox: typeof import('primevue/checkbox')['default']
    PrimeVueDialog: typeof import('primevue/dialog')['default']
    PrimeVueFileUpload: typeof import('primevue/fileupload')['default']
    PrimeVueIconField: typeof import('primevue/iconfield')['default']
    PrimeVueInputIcon: typeof import('primevue/inputicon')['default']
    PrimeVueInputText: typeof import('primevue/inputtext')['default']
    PrimeVueMenu: typeof import('primevue/menu')['default']
    PrimeVueRadioButton: typeof import('primevue/radiobutton')['default']
    PrimeVueSkeleton: typeof import('primevue/skeleton')['default']
    PrimeVueTextarea: typeof import('primevue/textarea')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
